server:
  port: 8081
mybatis:
  type-aliases-package: com.houxiang.webbiserver.model
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wenbi?characterEncoding=UTF-8
    username: root
    password: 123456789
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource